### PR TITLE
Added support for API 2015-04-07

### PR DESCRIPTION
**Pull request by confact**

### CODE REVIEW

**Comment by minter** [comment]
Any chance of getting this merged in? Seems like it would be very helpful.

**Comment by yas4891** [comment]
@minter 
It is still a mixture of Card and Source in the code: 
- there is still some mention of `card` in the code
- `last4` is an attribute specific to CC and not to to other sources

This works for now, because there are no other recurring options besides CC. It will break as soon as one other option is added. 

I'd love to fix it completely before merging as the current release version of koudoku works fine - to the best of my knowledge. Do you have any other experience?

**Comment by minter** [comment]
Not really - I'm getting my first product up on Stripe now. But if I start getting customers, I may be able to get a little deeper into the API.

**Comment by FanaHOVA** [comment]
Any update on what's going on with this? I installed the gem yesterday and was able to do a test payment, then I had issues with Devise and had to rollback to reinstall it and now it's giving me the card error, so random.

**Comment by yas4891** [comment]
@FanaHOVA Can you please open up a separate issue for this? Please include a backtrace.

**Comment by confact** [comment]
I forgot to merge my last changes, the problem when working on two computers. This works on my Rails app. I can help to support for other sources if you want, @yas4891?

**Comment by yas4891** [comment]
@confact I'd love to see some code that properly addresses the issue of different sources. Go for it

**Comment by confact** [comment]
@yas4891 I'll come up with something when I have time. :)

**Comment by trongrg** [comment]
(+1) My new Stripe account is now default to API version 2015-04-07, so it would be great if this PR can be merged

**Comment by emilkarl** [comment]
Anyone got some progress on this issue?

**Comment by andrewculver** [comment]
Hey all, sorry for the long time coming on this update, but we've got updated API support in #184 . Thanks for prodding us on this!

**Pull request closed without merging**
