### PR TITLE
feat: move strings to locale file

### PR DESCRIPTION
**Pull request by mediavrog**
Moved the messages and strings into a locale file, so they can be overwritten by anyone implementing koudoku. Most important part was having internationalized messages the subscription controller, as much of it can be reused even when subclassing

### CODE REVIEW

**Comment by pcboy** [comment]
Looks like a pretty good addition to me :+1:

**Comment by shawila** [comment]
:+1:

**Comment by yas4891** [comment]
Hi!

Thanks for your contribution. I really like it overall, but one thing that worries me immensely (and why I will NOT merge it in the current state) is missing backwards compatibility. 

This PR deletes `subscription#describe_difference` and replaces it with `application_helper#plan_difference`. If you can re-write it without changing the interface of `subscription`, I'm totally game to merge it. 

Also, I don't think there is a need to i18n the default views - e.g. `_social_proof`. I don't think anyone is really using those in a production environment.

**Comment by mediavrog** [comment]
@yas4891 Thanks for the feedback.
I moved the difference method back to the model.

I left the translations in the template views for the out-of-the-box experience, which makes koudoku quick to adapt even with few changes in the view.

**Pull request merged**
